name = "ADMetricEvaluation"
uuid = "142cbc84-d93d-11e8-01fa-3d89fcb4591f"
authors = ["vit.skvara <vit.skvara@gmail.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ScikitLearn = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
